import type { Metadata } from "next";
import Sidebar from "../components/Sidebar";
import Header from "../components/ui/Header";
// import "./globals.css";
import styles from "@/styles/recruitment.module.css"
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <main className={styles.layout}>
        <div className={styles.layout_left}>
            <Sidebar />
        </div>
        <div className={styles.layout_right}>
            <Header />
            <div className={styles.layout_content}>
                {children}
            </div>
        </div>
    </main>
}
