import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import temp_logo from "../temp_logo.svg"
const inter = Inter({ subsets: ["latin"] });
import styles from "@/styles/onboarding.module.css"
import Image from "next/image";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OnboardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${styles.onboarding_layout_wrapper} w-full h-full`} >
      <div className={styles.onboarding_layout_image_container}>
      </div>
      <div className={styles.onboarding_layout_form_wrapper}>
        <div className={styles.onboarding_layout_logo_container}>
          <Image src={temp_logo} alt="temp-logo" />
        </div>
        <div className={styles.onboarding_layout_form_container}>
          {children}
        </div>
      </div>
    </main>
  );
}

